# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'default'

steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: dockerhub
- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    repository: clintcolding/serverinfo
- task: Docker@2
  displayName: Logout of Docker Hub
  inputs:
    command: logout
    containerRegistry: dockerhub